name       : perl-net-http
version    : '6.18'
release    : 6
source     :
    - https://github.com/libwww-perl/Net-HTTP/archive/v6.18.tar.gz : f48e61d959b7201d438f3bfeee9f64b57882116c2de1a34d949ab315ae281ed8
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Net::HTTP - Low-level HTTP connection (client)
description: |
    Net::HTTP - Low-level HTTP connection (client)
patterns   :
    - /usr/share/man
builddeps  :
    - perl-uri
rundeps    :
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
