name       : perl-net-http
version    : '6.18'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.18.tar.gz : 7e42df2db7adce3e0eb4f78b88c450f453f5380f120fd5411232e03374ba951c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Net::HTTP - Low-level HTTP connection (client)
description: |
    Net::HTTP - Low-level HTTP connection (client)
builddeps  :
    - perl-io-socket-ssl
    - perl-uri
rundeps    :
    - perl-io-socket-ssl
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
