name       : perl-net-http
version    : '6.23'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.23.tar.gz : 0d65c09dd6c8589b2ae1118174d3c1a61703b6ecfc14a3442a8c74af65e0c94e
homepage   : https://metacpan.org/pod/Net::HTTP
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Net::HTTP - Low-level HTTP connection (client)
description: |
    The Net::HTTP class is a low-level HTTP client. An instance of the Net::HTTP class represents a connection to an HTTP server. The HTTP protocol is described in RFC 2616. The Net::HTTP class supports HTTP/1.0 and HTTP/1.1.
builddeps  :
    - perl-io-socket-ssl
    - perl-uri
rundeps    :
    - perl-io-socket-ssl
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
