name       : perl-net-http
version    : 6.09
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/Net-HTTP-6.09.tar.gz : 52762b939d84806908ba544581c5708375f7938c3c0e496c128ca3fbc425e58d
license    : Artistic-1.0-Perl
summary    : |
    Net::HTTP - Low-level HTTP connection (client)
description: |
    Net::HTTP - Low-level HTTP connection (client)
patterns   :
    - /usr/share/man
setup      : |
    perl Makefile.PL
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/lib/perl5/5.20.1
