name       : perl-net-http
version    : '6.19'
release    : 11
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.19.tar.gz : 52b76ec13959522cae64d965f15da3d99dcb445eddd85d2ce4e4f4df385b2fc4
homepage   : https://metacpan.org/pod/Net::HTTP
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Net::HTTP - Low-level HTTP connection (client)
description: |
    Net::HTTP - Low-level HTTP connection (client)
builddeps  :
    - perl-io-socket-ssl
    - perl-uri
rundeps    :
    - perl-io-socket-ssl
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
